### ISSUE TITLE
I got a crash that appears to realate to this mod

### ISSUE THREAD

**Issue by marted** [CannibalVox/DimDoors#26] opened 2015-04-03 20:01 UTC
I get this crash when opening a world I was using

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 4/3/15 3:54 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at StevenDimDoors.mod_pocketDim.core.PocketManager.createAndRegisterBlacklist(PocketManager.java:715)
	at StevenDimDoors.mod_pocketDim.saving.DDSaveHandler.loadAll(DDSaveHandler.java:59)
	at StevenDimDoors.mod_pocketDim.core.PocketManager.loadInternal(PocketManager.java:390)
	at StevenDimDoors.mod_pocketDim.core.PocketManager.load(PocketManager.java:192)
	at StevenDimDoors.mod_pocketDim.EventHookContainer.onWorldLoad(EventHookContainer.java:124)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_21_EventHookContainer_onWorldLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 193006728 bytes (184 MB) / 366403584 bytes (349 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 31 mods loaded, 31 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	deconstruction{2.2.5} [The Deconstruction Mod] ([MC1.7.10]deconstruction[v2.2.5].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	craftguide{1.6.8.1} [CraftGuide] (craftguide-1.6.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	dimdoors{2.2.5-test} [Dimensional Doors] (DimensionalDoors-2.2.5-test8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ganysend{1.8.3} [Gany's End] (Ganys End-1.8.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ganysnether{1.7.3} [Gany's Nether] (Ganys Nether-1.7.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ssHookShot{0} [HookShot] (Hook-Shot-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	mod_Invasion{1.1.2} [Invasion] (Invasion_1.1.2_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ObsidianBoat{v1.3.2} [Obsidian Boat] (ObsidianBoat-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Oceancraft{1.4.1} [Oceancraft] (Oceancraft-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	harvestcraft{1.7.10g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Rediscovered{1.0.1} [Minecraft Rediscovered Mod] (Rediscovered-1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Roguelike{1.3.6} [Roguelike Dungeons] (Roguelike-Dungeons-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	shipwrecks_winslow{1.6.2} [Shipwrecks!] (Shipwrecks-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	HungerOverhaul{1.7.10-beta.5.jenkins47} [Hunger Overhaul] (HungerOverhaul-1.7.10-beta.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by DPxKnightxZero** [comment] 2015-04-03 20:05
Already known.

**Comment by marted** [comment] 2015-04-03 20:08
so I'm just fucked until it gets fixed?

**Comment by DPxKnightxZero** [comment] 2015-04-19 23:49
#FIXTHISBUMP 

Alright so this needs to get fixed before its usable bumping thread!

**Comment by Codyworlds** [comment] 2015-06-03 14:25
I found out what you did to make this problem. Basically, you loaded one world, closed it, then loaded another one. The only workaround I can find is restarting Minecraft when it crashes.

**Comment by CannibalVox** [comment] 2015-07-19 14:39
Dupe of #35

**Closed by CannibalVox** 2015-07-19 14:39 UTC
